### ISSUE TITLE
Quake 1.06 not loading....

### ISSUE THREAD

**Issue by retro-wertz** [libretro/tyrquake#37]
first bad commit https://github.com/libretro/tyrquake/commit/3a6a1badfd0452ef10c180c5f8203c64ebbf8e2a

windows 10 x64
gcc 6.3.0

@Tatsuya79

**Comment by Tatsuya79** [comment]
Thanks we found it too.

I had to remove "id1" in common.c and all that "else if" part in libretro.c.
We'll have to see if extension are still working, I don't have any to try.
