### ISSUE TITLE
Adding music files.

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/tyrquake#39]
Folder structure:

Game Folder: 
-id1 (main game)
-hipnotic
-rogue
-quoth

Each folder can contain a "music" folder with bgm tracks. Ogg and Flac tested working on win7 x64.
The music files can be downloaded [from here.](https://steamcommunity.com/sharedfiles/filedetails/?id=119489135)
If they are free perhaps they could be added into the content downloader?
Only the ogg files and perhaps a note with where they should be copied to.

**Comment by atsumori666** [comment]
Is this a guide on how to add music or a bug report on not being able to add music?  I ask because in ios9 using a build circa Aug 9, 2017 I am not getting any sound when I add the music to, for example, id1/music.  Has this been verified to work in retroarch already?

**Comment by Tatsuya79** [comment]
That's a reminder and suggestion post.
Music works here in id1/music/track02.ogg ~ track11.ogg.
But I'm on win7 and there could be an issue with ios path.

**Comment by atsumori666** [comment]
Ok, thanks, I'll post a separate issue then for the iOS issue.
