### ISSUE TITLE
Loading PAK0.PAK (all caps) fails on Linux

### ISSUE THREAD

**Issue by hooby3dfx** [libretro/tyrquake#41]
I copied ID1/ PAK0.PAK and PAK1.PAK from a working DOS install.
Retroarch running in Lakka (Linux) would not load them.
After renaming them with lowercase they would load fine.

**Comment by retro-wertz** [comment]
because its suppose to be id1, not id only

**Comment by hooby3dfx** [comment]
Sorry, typo in OP.

**Comment by Tatsuya79** [comment]
Is that tolower method supposed to work like that [here](https://github.com/libretro/tyrquake/blob/master/common/libretro.c#L837)?

**Comment by Kivutar** [comment]
Renaming PAK0.PAK to pak0.pak doesn't work for me. Is it the only file needed?

**Comment by retro-wertz** [comment]
quake folder and related subfolders and pak files should be lowercase
e.g.
quake -> id1 -> pak0.pak, pak1.pak etc
quake -> hispanic-> pak0.pak, pak1.pak etc
quake -> quoth-> pak0.pak, pak1.pak etc

**Comment by Kivutar** [comment]
OK. I'm able to run the shareware version from the buildbot with the uppercase name on my Arch Linux.
