### ISSUE TITLE
No Music in iOS

### ISSUE THREAD

**Issue by SpiralCut** [libretro/tyrquake#48]
TyrQuake using a build circa 8/9 and on Retroarch 1.6.4 on iOS 10.3.3 does not load music.  I've tried ogg and mp3, I've tried adding into the id1/music folder, id1 folder, and system folder, and I have tried using music from both the quake site and files I have working on my PC and it does not seem to load at all.

**Comment by greatant** [comment]
Are the music files named using any upper-case letters by chance?
