### ISSUE TITLE
[Wii U ] Enhancement inverted y axis toggle

### ISSUE THREAD

**Issue by cucholix** [libretro/tyrquake#49]
The new build from 1.6.5 allows to use "new layout" feature to use both sticks in game, left stick to move the character and right stick to look, however the input for both are hardcoded so it's not possible configure them. 

The main problem is with the right stick, the y axis is inverted: down to look up, up to look down. It would be pretty useful add an option in core settings to enable/disable invert y axis.

**Comment by Gurk232** [comment]
Having an option to change stick sensitivity would also be much appreciated.

**Comment by ShadowOne333** [comment]
I am also having the same issue.
It seems the Invert or mouse option in-game is not working.

Having an option in the controls to enable or disable the Y Axis would do as cucholix said.
