### ISSUE TITLE
SuperQOT mod?

### ISSUE THREAD

**Issue by BenMcLean** [libretro/tyrquake#50]
The SUPERHOT team made [a cool mod for singleplayer Quake a few years ago](https://superhotgame.com/SUPERQOT/). It is very fun to play.

[I put their source code up on Github because GPL](https://github.com/BenMcLean/darkplaces-SUPERQOT). Unfortunately, their code has not been merged into the DarkPlaces Quake engine it's based on and certainly hasn't been a thing in tyrquake. Still, would a libretro version of SUPERQOT be feasible?

**Comment by greatant** [comment]
Feature request isn't an issue.

**Comment by BenMcLean** [comment]
Oh, OK. Where should feature requests go?

**Comment by BenMcLean** [comment]
I don't have it open at the moment, but I seem to remember tyrquake having some kind of on-off switch for the Quake Rally and Quake Matrix mod settings and that this also worked in lr-tyrquake. Seems like a similar switch for SuperQOT mod settings would be nice to have. Unless I am misinformed either about these what these mod switches did or what SuperQOT did.

**Comment by greatant** [comment]
A quick google shows you posting about this elsewhere. You are misremembering a darkplaces feature you found about a year ago.

My point is that this is an issue tracker. Not a place to submit feature requests or ask for help.

**Comment by BenMcLean** [comment]
Oh, OK, I haven't looked at it in a while 

Lots of projects use Github's issue tracker feature for things like that. If this one doesn't, fine whatever.

**Comment by greatant** [comment]
Example of proper github feature requests: https://github.com/marbl/canu/projects/1

It's not hard to setup. No one is voluntarily using the issue tracker for feature requests and liking it.
