### ISSUE TITLE
Can't move in the menu with the keyboard.

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/tyrquake#65]
You can not select menu items any more when controls are on kb/mouse for player1.
Not sure when that happened.

**Comment by ehmry** [comment]
Could be related to the keyboard event callback 4c381ede0a28690907e8b1d51af2c64374785790?

**Comment by Tatsuya79** [comment]
Yes that's it.
[Why is it disabled here?](https://github.com/libretro/tyrquake/commit/4c381ede0a28690907e8b1d51af2c64374785790#diff-6063ffc9a9449626349b38c0611c7454R586)

**Comment by ehmry** [comment]
I disabled it because I was getting double arrow key handling from the keyboard callback and `retro_input_state`, it could be that the frontend is not sending RETROK_UP/RETROK_UP events.

**Comment by ehmry** [comment]
Yea, thats looks good, the input device can be set to RETRO_DEVICE_MOUSE.

**Comment by ehmry** [comment]
Maybe ` retro_set_controller_port_device` should take both MOUSE and KEYBOARD?
 
https://github.com/libretro/tyrquake/blob/5aa8c55d64320260ca06ae87b5f1eadf8d297912/common/libretro.c#L425

**Comment by Tatsuya79** [comment]
I don't think that's really needed about the mouse?
It's already working alongside the keyboard.
