### ISSUE TITLE
Broken framerate since recen commit

### ISSUE THREAD

**Issue by vanfanel** [libretro/tyrquake#70]
Hi there,

I have just built latest sources, and framerate is plain wrong. It's like running a 50FPS game on a ~60Hz display: movement is jerky and uneven.
Also, using max_swapchain=2 makes the game run at half the speed.

All this has started happening exactly from this commit onwards:
https://github.com/libretro/tyrquake/commit/f83d35ffb2c8abcd38d49f9104c12ff9cde26b9b

I am using latest stable RetroArch 1.7.5, and this happens both on ARM64 and X86_64 using GNU/Linux on KMSDRM mode.

**Comment by Tatsuya79** [comment]
@twinaphex Did your tests for adding a 120hz mode ended there by mistake?
https://github.com/libretro/tyrquake/commit/f83d35ffb2c8abcd38d49f9104c12ff9cde26b9b#diff-6063ffc9a9449626349b38c0611c7454R177
